# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Finds the SFS from a given solution of P and E
#'
#' @param P One of the factorized two matrices, which will control the stopping criteria
#' @param E The other of the facotrized matrizes
#' @param maxIter The maximum number of iterations
#' @param check Number of iterations between checking to stop
#' @param beta The two shape parameters in the be3ta distribution to sample lambda
#' @param eps Epsilon for the stopping criteria
#'      
#' @return A list of outputs from the sampleSFS function
#' \itemize{
#'         \item avgChangeFinal     - final average change for each entrance in P
#'         \item avgChangeEachCheck - average change for each entrance in P at each check
#'         \item totalIter          - total number of iterations needed for convergence of the average change
#'         \item Pminimum           - minimum for each entry in P
#'         \item Pmaximum           - maximum for each entry in P
#'         \item Eminimum           - minimum for each entry in E
#'         \item Emaximum           - maximum for each entry in E
#'         \item P_lastCheckResults - results of P for the last 'check' iterations 
#'         \item E_lastCheckResults - results of E for the last 'check' iterations 
#'         }
#'
sampleSFS <- function(P, E, maxIter = 10^5L, check = 1000L, beta = 0.5, eps = 0.00001) {
    .Call(`_SFS_sampleSFS`, P, E, maxIter, check, beta, eps)
}

